#include <pcap.h>
#include <stdio.h>
#include <ctype.h>
#include <errno.h>
#include <stdlib.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <arpa/inet.h>
#include <sys/time.h>
#include <time.h>
#include <netinet/in.h>
#include <string.h>

#define SIZE 50000


FILE * fOut;
char* file = "fileRule2";


int main(int argc, char *argv[]){

	fOut = fopen (file,"w");


	//IPtables
	fprintf(fOut, "# Generated by iptables-save v1.6.0 on Sat Mar 10 20:59:58 2018\n*filter\n:INPUT ACCEPT [0:0]\n:FORWARD ACCEPT [0:0]\n:OUTPUT ACCEPT [0:0]\n");

	int i = 0;

	for(i = 0; i<SIZE; i++){
		int one = rand() % 255;
		int two = rand() % 255;
		int three = rand() % 255;

		fprintf(fOut,  "-A INPUT -s 1.%d.%d.%d -j DROP\n",one,two,three);

	}

	fprintf(fOut, "COMMIT\n# Completed on Sat Mar 10 20:59:58 2018\n");
	


	
	fclose(fOut);


	return(0);
  }
